### ISSUE TITLE
JOSS REVIEW: Not able to retrieve statmap from neurovault

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#93]
Running `STAT_IMG = fetch_neurovault_motor_task().images[0]` in the example notebook and unit tests fails for me. Here's the full traceback:

```
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nilearn-0.5.0-py3.7.egg/nilearn/datasets/neurovault.py", line 1008, in _get_batch
    resp = opener.open(request, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-a5e164ce6739> in <module>()
      2 from nilearn.datasets import fetch_neurovault_motor_task
      3 motor_images = fetch_neurovault_motor_task()
----> 4 stat_img = motor_images.images[0]

IndexError: list index out of range
```

**Comment by miykael** [comment]
This is not directly an `atlasreader` issue, but related to `nilearn`. But this needs to be solved nonetheless.

The `[SSL: CERTIFICATE_VERIFY_FAILED]` error implies that it cannot download the example dataset via `nilearn`. Can you run the following code:

```python
from nilearn.datasets import fetch_neurovault_motor_task
motor_images = fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
```

*Side note*: This is exactly one of the reason why we prefer to have the atlases distributed within the toolbox (as discussed here https://github.com/miykael/atlasreader/issues/97).

**Comment by miykael** [comment]
Alternatively, I could also link to a mybinder.org instance, such as this one: https://mybinder.org/v2/gh/miykael/atlasreader/joss_corrections?filepath=notebooks%2Fatlasreader.ipynb

To make sure that users can explore the toolbox before installing on their system.

**Comment by andrewheusser** [comment]
Adding the binder link to the readme would be great.  The code snippet you posted above doesn't work for me (same error). I'll try to figure out why later tonight when I have some time. In the meantime, have you tested the package with Python 3.7 (wondering if that might be the issue).

**Comment by miykael** [comment]
It took me some time to figure out the right travis-config specification, but Travis is now testing the toolbox for python version 3.6 and 3.7. And as can be seen [here](https://travis-ci.org/miykael/atlasreader/builds/495680421), these tests currently pass.

Therefore, the issue doesn't seem to be because of Python 3.7, but might be related to OSX (at least according to the 2nd answer [here](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)).

Commit https://github.com/miykael/atlasreader/pull/99/commits/87057741314e50c4a8c03c7fb9629de139dcde87 added now a link to mybinder.org, to allow for interactive exploration of the toolbox.

**Comment by andrewheusser** [comment]
Thanks for the lead. Running the command posted [here](https://stackoverflow.com/a/42334357) ultimately fixed the issue.  Not a atlasreader or nilearn issue, so closing this and proceeding with review. 

👍for adding binder link
